require './db.rb'
require './models.rb'

desc 'Create Database'
namespace :db do
  desc 'Create Talbes'
  task :create do
    SaharaOmsSchema.migrate(:up)
  end

  desc 'Drop Tables'
  task :drop do
    SaharaOmsSchema.migrate(:down)
  end

  desc 'Seeds'
  task :seeds do
    require './seeds.rb'
  end

  desc 'List all data'
  task :list do
    p Order.all
  end

  desc 'Reset databse'
  task :reset do
    SaharaOmsSchema.migrate(:down)
    SaharaOmsSchema.migrate(:up)
    require './seeds.rb'
  end
end
