apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  containers: 
    - resources:
        limits :
          cpu: 0.5
      image: noralife/sahara-db
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports: 
        - containerPort: 3306
          name: mysql
