apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  replicas: 1
  selector:
    name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers: 
      - name: mysql
        image: noralife/sahara-db
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        ports: 
          - containerPort: 3306
            name: mysql
