apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: sahara-cms
  name: sahara-cms
spec: 
  ports:
    # the port that this service should serve on
    - port: 3001
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: sahara-cms
  type: LoadBalancer
