apiVersion: v1
kind: Pod
metadata:
  name: sahara-web
  labels:
    name: sahara-web
spec:
  containers:
    - image: noralife/sahara-web
      name: sahara-web
      ports:
        - containerPort: 80
          name: sahara-web
