apiVersion: v1
kind: Pod
metadata:
  name: sahara-cms
  labels: 
    name: sahara-cms
spec: 
  containers: 
    - image: noralife/sahara-cms
      name: sahara-cms
      env:
      - name: SAHARA_ENV
        value: production
      - name: DB_PORT_3306_TCP_ADDR
        value: mysql
      - name: MYSQL_ROOT_PASSWORD
        value: root
      - name: DB_PORT_3306_TCP_PORT
        value: '3306'
      ports: 
        - containerPort: 30301
          name: sahara-cms
