apiVersion: v1
kind: ReplicationController
metadata:
  name: sahara-pms
  labels: 
    name: sahara-pms
spec: 
  replicas: 1
  selector:
    name: sahara-pms
  template:
    metadata:
      labels:
        name: sahara-pms
    spec:
      containers: 
      - name: sahara-pms
        image: noralife/sahara-pms
        env:
        - name: SAHARA_ENV
          value: production
        - name: DB_PORT_3306_TCP_ADDR
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: DB_PORT_3306_TCP_PORT
          value: '3306'
        - name: CMS_PORT_30301_TCP_ADDR
          value: sahara-cms
        - name: CMS_PORT_30301_TCP_PORT
          value: '30301'
        ports: 
          - containerPort: 30302
            name: sahara-pms
